module.exports = {
    lici: {
        primary: {
            active: { value: "{color.blue.cornflower.400.value}" },
            hover: { value: "{color.blue.cornflower.600.value}" },
            inactive: { value: "{color.blue.cornflower.100.value}" }
        },
        feedback: {
            success: { value: "{color.green.jade.400.value}" },
            warning: { value: "{color.yellow.sunshine.500.value}" },
            error : { value: "{color.red.cadmio.300.value}" },
            info: { value: "{color.blue.cornflower.200.value}" },
        },
        font: {
            primary: { value: "{color.gray.800.value}" },
            secondary: { value: "{color.gray.500.value}" },
            strong: { value: "{color.gray.400.value}" },
            hint: { value: "{color.gray.300.value}" },
            disable: { value: "{color.gray.200.value}" },
            overDark: { value: "{color.gray.000.value}" },
            action: { value: "{color.blue.cornflower.400.value}" },
            success: { value: "{color.green.jade.500.value}" },
            error: { value: "{color.red.cadmio.500.value}" },
        },
        background: {
            white: { value: "{color.gray.000.value}" },
            soft: { value: "{color.gray.100.value}" },
            medium: { value: "{color.gray.200.value}" },
            hint: { value: "{color.gray.300.value}" },
            strong: { value: "{color.gray.400.value}" },
        },
        comp: {
            one: {
                lighten4: { value: "{color.lilac.lavender.000.value}" },
                lighten3: { value: "{color.lilac.lavender.100.value}" },
                lighten2: { value: "{color.lilac.lavender.200.value}" },
                lighten1: { value: "{color.lilac.lavender.300.value}" },
                base: { value: "{color.lilac.lavender.400.value}" },
                darken1: { value: "{color.lilac.lavender.500.value}" },
                darken2: { value: "{color.lilac.lavender.600.value}" },
                darken3: { value: "{color.lilac.lavender.700.value}" },
                darken4: { value: "{color.lilac.lavender.800.value}" },
                darken5: { value: "{color.lilac.lavender.900.value}" },
             },
            two: {
                lighten5: { value: "{color.yellow.sunshine.000.value}" },
                lighten4: { value: "{color.yellow.sunshine.100.value}" },
                lighten3: { value: "{color.yellow.sunshine.200.value}" },
                lighten2: { value: "{color.yellow.sunshine.300.value}" },
                lighten1: { value: "{color.yellow.sunshine.400.value}" },
                base: { value: "{color.yellow.sunshine.500.value}" },
                darken1: { value: "{color.yellow.sunshine.600.value}" },
                darken2: { value: "{color.yellow.sunshine.700.value}" },
                darken3: { value: "{color.yellow.sunshine.800.value}" },
                darken4: { value: "{color.yellow.sunshine.900.value}" },
            },
            three: {
                lighten5: { value: "{color.green.jade.000.value}" },
                lighten4: { value: "{color.green.jade.100.value}" },
                lighten3: { value: "{color.green.jade.200.value}" },
                lighten2: { value: "{color.green.jade.300.value}" },
                lighten1: { value: "{color.green.jade.400.value}" },
                base: { value: "{color.green.jade.500.value}" },
                darken1: { value: "{color.green.jade.600.value}" },
                darken2: { value: "{color.green.jade.700.value}" },
                darken3: { value: "{color.green.jade.800.value}" },
                darken4: { value: "{color.green.jade.900.value}" },
            },
            four: {
                lighten5: { value: "{color.red.cadmio.000.value}" },
                lighten4: { value: "{color.red.cadmio.100.value}" },
                lighten3: { value: "{color.red.cadmio.200.value}" },
                lighten2: { value: "{color.red.cadmio.300.value}" },
                lighten1: { value: "{color.red.cadmio.400.value}" },
                base: { value: "{color.red.cadmio.500.value}" },
                darken1: { value: "{color.red.cadmio.600.value}" },
                darken2: { value: "{color.red.cadmio.700.value}" },
                darken3: { value: "{color.red.cadmio.800.value}" },
                darken4: { value: "{color.red.cadmio.900.value}" },
                accentLighten2:{value: "{color.red.accentCadmio.200.value}"}
            },
            five: {
                lighten4: { value: "{color.blue.cornflower.000.value}" },
                lighten3: { value: "{color.blue.cornflower.100.value}" },
                lighten2: { value: "{color.blue.cornflower.200.value}" },
                lighten1: { value: "{color.blue.cornflower.300.value}" },
                base: { value: "{color.blue.cornflower.400.value}" },
                darken1: { value: "{color.blue.cornflower.500.value}" },
                darken2: { value: "{color.blue.cornflower.600.value}" },
                darken3: { value: "{color.blue.cornflower.700.value}" },
                darken4: { value: "{color.blue.cornflower.800.value}" },
                darken5: { value: "{color.blue.cornflower.900.value}" },
            }
        },
        gray: {
            lighten5: { value: "{color.gray.000.value}" },
            lighten4: { value: "{color.gray.100.value}" },
            lighten3: { value: "{color.gray.200.value}" },
            lighten2: { value: "{color.gray.300.value}" },
            lighten1: { value: "{color.gray.400.value}" },
            base: { value: "{color.gray.500.value}" },
            darken1: { value: "{color.gray.600.value}" },
            darken2: { value: "{color.gray.700.value}" },
            darken3: { value: "{color.gray.800.value}" },
            darken4: { value: "{color.gray.900.value}" },
        },
        black: { value: "{color.black.normal.value}" },
        white: { value: "{color.white.normal.value}" }
    },
};
